server:
  port: 18080

spring:
  application:
    name: home-service

patient:
  service:
    url: http://localhost:8081

doctor:
  service:
    url: http://localhost:8082

appointment:
  service:
    url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
