server:
  port: 18080

spring:
  application:
    name: home-service
  datasource:
    url: jdbc:postgresql://localhost:5432/hospitaldb
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgresnew
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

patient:
  service:
    url: http://localhost:8081

doctor:
  service:
    url: http://localhost:8082

appointment:
  service:
    url: http://localhost:8083

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
